// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/irvanrifai/mkp-backend-development-test/api-ticketing/models"
	mock "github.com/stretchr/testify/mock"
)

// IEventRepository is an autogenerated mock type for the IEventRepository type
type IEventRepository struct {
	mock.Mock
}

type IEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IEventRepository) EXPECT() *IEventRepository_Expecter {
	return &IEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *IEventRepository) Create(_a0 *models.Event) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *models.Event
func (_e *IEventRepository_Expecter) Create(_a0 interface{}) *IEventRepository_Create_Call {
	return &IEventRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *IEventRepository_Create_Call) Run(run func(_a0 *models.Event)) *IEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Event))
	})
	return _c
}

func (_c *IEventRepository_Create_Call) Return(_a0 error) *IEventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEventRepository_Create_Call) RunAndReturn(run func(*models.Event) error) *IEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *IEventRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IEventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IEventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *IEventRepository_Expecter) Delete(id interface{}) *IEventRepository_Delete_Call {
	return &IEventRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *IEventRepository_Delete_Call) Run(run func(id uint)) *IEventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *IEventRepository_Delete_Call) Return(_a0 error) *IEventRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEventRepository_Delete_Call) RunAndReturn(run func(uint) error) *IEventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *IEventRepository) FindAll() ([]models.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEventRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type IEventRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *IEventRepository_Expecter) FindAll() *IEventRepository_FindAll_Call {
	return &IEventRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *IEventRepository_FindAll_Call) Run(run func()) *IEventRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEventRepository_FindAll_Call) Return(_a0 []models.Event, _a1 error) *IEventRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEventRepository_FindAll_Call) RunAndReturn(run func() ([]models.Event, error)) *IEventRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *IEventRepository) FindByID(id uint) (models.Event, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (models.Event, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) models.Event); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Event)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEventRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type IEventRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *IEventRepository_Expecter) FindByID(id interface{}) *IEventRepository_FindByID_Call {
	return &IEventRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *IEventRepository_FindByID_Call) Run(run func(id uint)) *IEventRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *IEventRepository_FindByID_Call) Return(_a0 models.Event, _a1 error) *IEventRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEventRepository_FindByID_Call) RunAndReturn(run func(uint) (models.Event, error)) *IEventRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *IEventRepository) Update(_a0 *models.Event) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *models.Event
func (_e *IEventRepository_Expecter) Update(_a0 interface{}) *IEventRepository_Update_Call {
	return &IEventRepository_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *IEventRepository_Update_Call) Run(run func(_a0 *models.Event)) *IEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Event))
	})
	return _c
}

func (_c *IEventRepository_Update_Call) Return(_a0 error) *IEventRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEventRepository_Update_Call) RunAndReturn(run func(*models.Event) error) *IEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewIEventRepository creates a new instance of IEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEventRepository {
	mock := &IEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
