// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/irvanrifai/mkp-backend-development-test/api-ticketing/models"
	mock "github.com/stretchr/testify/mock"
)

// IEventUsecase is an autogenerated mock type for the IEventUsecase type
type IEventUsecase struct {
	mock.Mock
}

type IEventUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *IEventUsecase) EXPECT() *IEventUsecase_Expecter {
	return &IEventUsecase_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function with given fields: title, desc, creatorID
func (_m *IEventUsecase) AddEvent(title string, desc string, creatorID uint) (models.Event, error) {
	ret := _m.Called(title, desc, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for AddEvent")
	}

	var r0 models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, uint) (models.Event, error)); ok {
		return rf(title, desc, creatorID)
	}
	if rf, ok := ret.Get(0).(func(string, string, uint) models.Event); ok {
		r0 = rf(title, desc, creatorID)
	} else {
		r0 = ret.Get(0).(models.Event)
	}

	if rf, ok := ret.Get(1).(func(string, string, uint) error); ok {
		r1 = rf(title, desc, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEventUsecase_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type IEventUsecase_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - title string
//   - desc string
//   - creatorID uint
func (_e *IEventUsecase_Expecter) AddEvent(title interface{}, desc interface{}, creatorID interface{}) *IEventUsecase_AddEvent_Call {
	return &IEventUsecase_AddEvent_Call{Call: _e.mock.On("AddEvent", title, desc, creatorID)}
}

func (_c *IEventUsecase_AddEvent_Call) Run(run func(title string, desc string, creatorID uint)) *IEventUsecase_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *IEventUsecase_AddEvent_Call) Return(_a0 models.Event, _a1 error) *IEventUsecase_AddEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEventUsecase_AddEvent_Call) RunAndReturn(run func(string, string, uint) (models.Event, error)) *IEventUsecase_AddEvent_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllEvents provides a mock function with no fields
func (_m *IEventUsecase) FindAllEvents() ([]models.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllEvents")
	}

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEventUsecase_FindAllEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllEvents'
type IEventUsecase_FindAllEvents_Call struct {
	*mock.Call
}

// FindAllEvents is a helper method to define mock.On call
func (_e *IEventUsecase_Expecter) FindAllEvents() *IEventUsecase_FindAllEvents_Call {
	return &IEventUsecase_FindAllEvents_Call{Call: _e.mock.On("FindAllEvents")}
}

func (_c *IEventUsecase_FindAllEvents_Call) Run(run func()) *IEventUsecase_FindAllEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEventUsecase_FindAllEvents_Call) Return(_a0 []models.Event, _a1 error) *IEventUsecase_FindAllEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEventUsecase_FindAllEvents_Call) RunAndReturn(run func() ([]models.Event, error)) *IEventUsecase_FindAllEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewIEventUsecase creates a new instance of IEventUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEventUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEventUsecase {
	mock := &IEventUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
