// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/irvanrifai/mkp-backend-development-test/api-ticketing/models"
	mock "github.com/stretchr/testify/mock"
)

// IScheduleUsecase is an autogenerated mock type for the IScheduleUsecase type
type IScheduleUsecase struct {
	mock.Mock
}

type IScheduleUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *IScheduleUsecase) EXPECT() *IScheduleUsecase_Expecter {
	return &IScheduleUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *IScheduleUsecase) Create(_a0 models.Schedule) (models.Schedule, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Schedule) (models.Schedule, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.Schedule) models.Schedule); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Schedule)
	}

	if rf, ok := ret.Get(1).(func(models.Schedule) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IScheduleUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IScheduleUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 models.Schedule
func (_e *IScheduleUsecase_Expecter) Create(_a0 interface{}) *IScheduleUsecase_Create_Call {
	return &IScheduleUsecase_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *IScheduleUsecase_Create_Call) Run(run func(_a0 models.Schedule)) *IScheduleUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Schedule))
	})
	return _c
}

func (_c *IScheduleUsecase_Create_Call) Return(_a0 models.Schedule, _a1 error) *IScheduleUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IScheduleUsecase_Create_Call) RunAndReturn(run func(models.Schedule) (models.Schedule, error)) *IScheduleUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *IScheduleUsecase) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IScheduleUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IScheduleUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *IScheduleUsecase_Expecter) Delete(id interface{}) *IScheduleUsecase_Delete_Call {
	return &IScheduleUsecase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *IScheduleUsecase_Delete_Call) Run(run func(id uint)) *IScheduleUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *IScheduleUsecase_Delete_Call) Return(_a0 error) *IScheduleUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IScheduleUsecase_Delete_Call) RunAndReturn(run func(uint) error) *IScheduleUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with no fields
func (_m *IScheduleUsecase) FindAll() ([]models.Schedule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Schedule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Schedule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IScheduleUsecase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type IScheduleUsecase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *IScheduleUsecase_Expecter) FindAll() *IScheduleUsecase_FindAll_Call {
	return &IScheduleUsecase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *IScheduleUsecase_FindAll_Call) Run(run func()) *IScheduleUsecase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IScheduleUsecase_FindAll_Call) Return(_a0 []models.Schedule, _a1 error) *IScheduleUsecase_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IScheduleUsecase_FindAll_Call) RunAndReturn(run func() ([]models.Schedule, error)) *IScheduleUsecase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *IScheduleUsecase) FindByID(id uint) (models.Schedule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 models.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (models.Schedule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) models.Schedule); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Schedule)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IScheduleUsecase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type IScheduleUsecase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *IScheduleUsecase_Expecter) FindByID(id interface{}) *IScheduleUsecase_FindByID_Call {
	return &IScheduleUsecase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *IScheduleUsecase_FindByID_Call) Run(run func(id uint)) *IScheduleUsecase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *IScheduleUsecase_FindByID_Call) Return(_a0 models.Schedule, _a1 error) *IScheduleUsecase_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IScheduleUsecase_FindByID_Call) RunAndReturn(run func(uint) (models.Schedule, error)) *IScheduleUsecase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, _a1
func (_m *IScheduleUsecase) Update(id uint, _a1 models.Schedule) (models.Schedule, error) {
	ret := _m.Called(id, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, models.Schedule) (models.Schedule, error)); ok {
		return rf(id, _a1)
	}
	if rf, ok := ret.Get(0).(func(uint, models.Schedule) models.Schedule); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Get(0).(models.Schedule)
	}

	if rf, ok := ret.Get(1).(func(uint, models.Schedule) error); ok {
		r1 = rf(id, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IScheduleUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IScheduleUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - _a1 models.Schedule
func (_e *IScheduleUsecase_Expecter) Update(id interface{}, _a1 interface{}) *IScheduleUsecase_Update_Call {
	return &IScheduleUsecase_Update_Call{Call: _e.mock.On("Update", id, _a1)}
}

func (_c *IScheduleUsecase_Update_Call) Run(run func(id uint, _a1 models.Schedule)) *IScheduleUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(models.Schedule))
	})
	return _c
}

func (_c *IScheduleUsecase_Update_Call) Return(_a0 models.Schedule, _a1 error) *IScheduleUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IScheduleUsecase_Update_Call) RunAndReturn(run func(uint, models.Schedule) (models.Schedule, error)) *IScheduleUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewIScheduleUsecase creates a new instance of IScheduleUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIScheduleUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IScheduleUsecase {
	mock := &IScheduleUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
