// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/irvanrifai/mkp-backend-development-test/api-ticketing/models"
	mock "github.com/stretchr/testify/mock"
)

// IUserUsecase is an autogenerated mock type for the IUserUsecase type
type IUserUsecase struct {
	mock.Mock
}

type IUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserUsecase) EXPECT() *IUserUsecase_Expecter {
	return &IUserUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: email, password
func (_m *IUserUsecase) Login(email string, password string) (string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type IUserUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *IUserUsecase_Expecter) Login(email interface{}, password interface{}) *IUserUsecase_Login_Call {
	return &IUserUsecase_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *IUserUsecase_Login_Call) Run(run func(email string, password string)) *IUserUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *IUserUsecase_Login_Call) Return(_a0 string, _a1 error) *IUserUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserUsecase_Login_Call) RunAndReturn(run func(string, string) (string, error)) *IUserUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: name, username, email, password
func (_m *IUserUsecase) Register(name string, username string, email string, password string) (models.User, error) {
	ret := _m.Called(name, username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (models.User, error)); ok {
		return rf(name, username, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) models.User); ok {
		r0 = rf(name, username, email, password)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(name, username, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IUserUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - username string
//   - email string
//   - password string
func (_e *IUserUsecase_Expecter) Register(name interface{}, username interface{}, email interface{}, password interface{}) *IUserUsecase_Register_Call {
	return &IUserUsecase_Register_Call{Call: _e.mock.On("Register", name, username, email, password)}
}

func (_c *IUserUsecase_Register_Call) Run(run func(name string, username string, email string, password string)) *IUserUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IUserUsecase_Register_Call) Return(_a0 models.User, _a1 error) *IUserUsecase_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserUsecase_Register_Call) RunAndReturn(run func(string, string, string, string) (models.User, error)) *IUserUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUserUsecase creates a new instance of IUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserUsecase {
	mock := &IUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
